Question 1

In [26]:
class Employee:
  no_of_employees = 0
  name = ''
  family = ''
  salary = ''
  department = ''
  employees = []
  def __init__(self, name, family, salary, department):
    self.name = name
    self.family = family
    self.salary = salary
    self.department = department
    Employee.no_of_employees += 1
    Employee.employees.append([name, family, salary, department])
  def avg_salary():
    total_sal = sum([employee[2] for employee in Employee.employees])
    return round(total_sal/Employee.no_of_employees,2)

class FulltimeEmployee(Employee):
  pass

Employee('Vennela', 'Madamshetty', 50000, 'Data')
Employee('Tom', 'Peterson', 75000, 'Development')
FulltimeEmployee('Vishnu', 'Vardhan', 36000, 'Testing')
print('Average salary of employees:',Employee.avg_salary())
print('Average salary of employees by calling method using subclass:',FulltimeEmployee.avg_salary())

Average salary of employees: 53666.67
Average salary of employees by calling method using subclass: 53666.67


Question 2

In [22]:
import numpy as np
vector = np.random.uniform(1,20,20)
arr = vector.reshape(4,5)
maxn = np.amax(arr, axis=1)
print('Original array:\n',arr)
print('\n\nArray after replacing max with 0:\n',np.where(np.isin(arr,maxn), 0, arr))

Original array:
 [[17.66079269 11.40603686  3.38888756  8.51817933 16.06243131]
 [18.93636549  9.63710031 19.62097997 16.00486548  7.43872821]
 [ 6.06111186  8.40660322 11.29008702  6.36097861  9.6371647 ]
 [ 7.41500954 17.22012552 12.76857919 14.6323253  11.32969974]]


Array after replacing max with 0:
 [[ 0.         11.40603686  3.38888756  8.51817933 16.06243131]
 [18.93636549  9.63710031  0.         16.00486548  7.43872821]
 [ 6.06111186  8.40660322  0.          6.36097861  9.6371647 ]
 [ 7.41500954  0.         12.76857919 14.6323253  11.32969974]]
